import Vue from "vue";
import BottomPrice from "@views.pc/components/BottomPrice";
import ProductCartPc from "@views.pc/components/ProductCartPc";
import ProductOrderPc from "@views.pc/components/ProductOrderPc";
import LayoutRight from "@views.pc/components/LayoutRight";
import AppliedDiscount from "@views.mobile/components/AppliedDiscount.vue";
import AppliedDiscountPc from "@views.pc/components/AppliedDiscountPc.vue";
import Reviewpc from "@views.pc/shop/components/ReviewPc.vue";
import ReviewListPc from "@views.pc/shop/components/ReviewListPc.vue";
import BrandFilter from "@views.pc/components/modal/BrandFilter";
Vue.component("bottom-price", BottomPrice);
Vue.component("product-cart-pc", ProductCartPc);
Vue.component("product-order-pc", ProductOrderPc);
Vue.component("layout-right", LayoutRight);
Vue.component("applied-discount", AppliedDiscount);
Vue.component("applied-discount-pc", AppliedDiscountPc);
Vue.component("review-pc", Reviewpc);
Vue.component("reviewlist-pc", ReviewListPc);
Vue.component("brand-filter", BrandFilter);
